DROP TABLE IF EXISTS sample_all_info;
DROP TABLE IF EXISTS warning_note_words;


CREATE TABLE models_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    model_name TEXT NOT NULL,
    features TEXT NOT NULL,
    base_model_name TEXT NOT NULL,
    valid_set_perform TEXT NOT NULL,
    perform_in_1w TEXT NOT NULL,
    training_status TEXT NOT NULL,
    use_data_ids TEXT NOT NULL,
    created TIMESTAMP DEFAULT (datetime('now','localtime'))
);

CREATE TABLE sample_all_info (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	task_code TEXT NOT NULL,
	sample_code TEXT NOT NULL,
    sample_concentration_ng_uL_ FLOAT,
    Sample_Volume_uL_ FLOAT,
    sample_basenumber FLOAT,
    _gt_Q30pct_total FLOAT,
    GCpct_total FLOAT,
    EstErrpct_total FLOAT,
    TotalReads_Mb FLOAT,
    TotalBases_Gb FLOAT,
    Read1_Q20_pct FLOAT,
    Read2_Q20_pct FLOAT,
    Read1_Q30_pct FLOAT,
    Read2_Q30_pct FLOAT,
    Read1_A_pct FLOAT,
    Read1_T_pct FLOAT,
    Read1_G_pct FLOAT,
    Read1_C_pct FLOAT,
    Read2_A_pct FLOAT,
    Read2_T_pct FLOAT,
    Read2_G_pct FLOAT,
    Read2_C_pct FLOAT,
    Read1BaseDiversity_AT_pct FLOAT,
    Read1BaseDiversity_GC_pct FLOAT,
    Read2BaseDiversity_AT_pct FLOAT,
    Read2BaseDiversity_GC_pct FLOAT,
    Max_N_content_pct FLOAT,
    GC_pct FLOAT,
    Clean_data_Raw_data_pct FLOAT,
    MappingRate_pct FLOAT,
    UniqueRate_pct FLOAT,
    DuplicateRate_pct FLOAT,
    MismatchRate_pct FLOAT,
    AveInsertSize FLOAT,
    SdInsertSize FLOAT,
    chr1_AveDepth_X FLOAT,
    chr2_AveDepth_X FLOAT,
    chr3_AveDepth_X FLOAT,
    chr4_AveDepth_X FLOAT,
    chr5_AveDepth_X FLOAT,
    chr6_AveDepth_X FLOAT,
    chr7_AveDepth_X FLOAT,
    chr8_AveDepth_X FLOAT,
    chr9_AveDepth_X FLOAT,
    chr10_AveDepth_X FLOAT,
    chr11_AveDepth_X FLOAT,
    chr12_AveDepth_X FLOAT,
    chr13_AveDepth_X FLOAT,
    chr14_AveDepth_X FLOAT,
    chr15_AveDepth_X FLOAT,
    chr16_AveDepth_X FLOAT,
    chr17_AveDepth_X FLOAT,
    chr18_AveDepth_X FLOAT,
    chr19_AveDepth_X FLOAT,
    chr20_AveDepth_X FLOAT,
    chr21_AveDepth_X FLOAT,
    chr22_AveDepth_X FLOAT,
    chrX_AveDepth_X FLOAT,
    chrY_AveDepth_X FLOAT,
    chrM_AveDepth_X FLOAT,
    AveDepth_X FLOAT,
    Sd_Autosome_Depth FLOAT,
    Range_Autosome_Depth_X FLOAT,
    Sd_Depth_Norm_Distribution FLOAT,
    _1X_Coverage_pct FLOAT,
    _5X_Coverage_pct FLOAT,
    _10X_Coverage_pct FLOAT,
    _20X_Coverage_pct FLOAT,
    _30X_Coverage_pct FLOAT,
    _40X_Coverage_pct FLOAT,
    _50X_Coverage_pct FLOAT,
    _60X_Coverage_pct FLOAT,
    _70X_Coverage_pct FLOAT,
    _80X_Coverage_pct FLOAT,
    _90X_Coverage_pct FLOAT,
    _100X_Coverage_pct FLOAT,
    SdCoverage FLOAT,
    SNP_Number FLOAT,
    SNP_in_dbSNP FLOAT,
    SNP_in_1KGP3 FLOAT,
    SNP_in_gnomAD_exomes FLOAT,
    SNP_in_gnomAD_genomes FLOAT,
    SNP_in_TOPMed FLOAT,
    SNP_in_ChinaMAP FLOAT,
    Novel_SNP FLOAT,
    Homozygous_SNP FLOAT,
    Heterozygous_SNP FLOAT,
    HIGH_impact_SNP FLOAT,
    MODERATE_impact_SNP FLOAT,
    LOW_impact_SNP FLOAT,
    MODIFIER_impact_SNP FLOAT,
    Het_Hom FLOAT,
    Ti_Tv FLOAT,
    INDEL_Number FLOAT,
    INDEL_in_dbSNP FLOAT,
    INDEL_in_1KGP3 FLOAT,
    INDEL_in_gnomAD_exomes FLOAT,
    INDEL_in_gnomAD_genomes FLOAT,
    INDEL_in_TOPMed FLOAT,
    INDEL_in_ChinaMAP FLOAT,
    Novel_INDEL FLOAT,
    Homozygous_INDEL FLOAT,
    Heterozygous_INDEL FLOAT,
    HIGH_impact_INDEL FLOAT,
    MODERATE_impact_INDEL FLOAT,
    LOW_impact_INDEL FLOAT,
    MODIFIER_impact_INDEL FLOAT,
    CNV_CNVnator_Number FLOAT,
    CNV_CNVnator_DUP_Length FLOAT,
    CNV_CNVnator_DEL_Length FLOAT,
    CNV_CNVnator_Anno_Number FLOAT,
    SV_lumpy_Number FLOAT,
    SV_lumpy_Anno_Number FLOAT,
    SV_delly_Number FLOAT,
    SV_delly_Anno_Number FLOAT,
    SV_manta_Number FLOAT,
    SV_manta_Anno_Number FLOAT,
    SV_MELT_Number FLOAT,
    SV_MELT_Anno_Number FLOAT,
    SV_Whamg_Number FLOAT,
    SV_Whamg_Anno_Number FLOAT,
    SV_xTea_Number FLOAT,
    SV_xTea_Anno_Number FLOAT,
    contamination_pct FLOAT,
    is_bad INTEGER,
    bad_note TEXT,
	Score FLOAT,
	Note_Warning TEXT,
	Judge TEXT,
	created TIMESTAMP DEFAULT (datetime('now','localtime'))
);


CREATE TABLE warning_note_words (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sample_table_id INTEGER NOT NULL,
	note_warning_word TEXT,
	Score FLOAT,
	Judge TEXT,
	created TIMESTAMP DEFAULT (datetime('now','localtime'))
);


-- CREATE TABLE sample_all_info (
-- 	id INTEGER PRIMARY KEY AUTOINCREMENT,
-- 	task_code TEXT NOT NULL,
-- 	sample_code TEXT NOT NULL,
--     Q30_pct FLOAT,
--     GC_pct FLOAT,
--     Max_N_Content_pct FLOAT,
--     TotalReads_Mb FLOAT,
--     TotalBases_Gb FLOAT,
--     Read1_Q20_pct FLOAT,
--     Read2_Q20_pct FLOAT,
--     Read1_Q30_pct FLOAT,
--     Read2_Q30_pct FLOAT,
--     Read1_A_pct FLOAT,
--     Read1_T_pct FLOAT,
--     Read1_G_pct FLOAT,
--     Read1_C_pct FLOAT,
--     Read2_A_pct FLOAT,
--     Read2_T_pct FLOAT,
--     Read2_G_pct FLOAT,
--     Read2_C_pct FLOAT,
--     Read1BaseDiversity_AT_pct FLOAT,
--     Read1BaseDiversity_GC_pct FLOAT,
--     Read2BaseDiversity_AT_pct FLOAT,
--     Read2BaseDiversity_GC_pct FLOAT,
--     Clean_data_Raw_data_pct FLOAT,
--     MappingRate_pct FLOAT,
--     UniqueRate_pct FLOAT,
--     DuplicateRate_pct FLOAT,
--     MismatchRate_pct FLOAT,
--     AveInsertSize FLOAT,
--     SdInsertSize FLOAT,
--     chr1_AveDepth_X FLOAT,
--     chr2_AveDepth_X FLOAT,
--     chr3_AveDepth_X FLOAT,
--     chr4_AveDepth_X FLOAT,
--     chr5_AveDepth_X FLOAT,
--     chr6_AveDepth_X FLOAT,
--     chr7_AveDepth_X FLOAT,
--     chr8_AveDepth_X FLOAT,
--     chr9_AveDepth_X FLOAT,
--     chr10_AveDepth_X FLOAT,
--     chr11_AveDepth_X FLOAT,
--     chr12_AveDepth_X FLOAT,
--     chr13_AveDepth_X FLOAT,
--     chr14_AveDepth_X FLOAT,
--     chr15_AveDepth_X FLOAT,
--     chr16_AveDepth_X FLOAT,
--     chr17_AveDepth_X FLOAT,
--     chr18_AveDepth_X FLOAT,
--     chr19_AveDepth_X FLOAT,
--     chr20_AveDepth_X FLOAT,
--     chr21_AveDepth_X FLOAT,
--     chr22_AveDepth_X FLOAT,
--     chrM_AveDepth_X FLOAT,
--     AveDepth_X FLOAT,
--     Sd_Autosome_Depth FLOAT,
--     Range_Autosome_Depth_X FLOAT,
--     Sd_Depth_Norm_Distribution FLOAT,
--     _1X_Coverage_pct FLOAT,
--     _5X_Coverage_pct FLOAT,
--     _10X_Coverage_pct FLOAT,
--     _20X_Coverage_pct FLOAT,
--     _30X_Coverage_pct FLOAT,
--     _40X_Coverage_pct FLOAT,
--     _50X_Coverage_pct FLOAT,
--     _60X_Coverage_pct FLOAT,
--     _70X_Coverage_pct FLOAT,
--     _80X_Coverage_pct FLOAT,
--     _90X_Coverage_pct FLOAT,
--     _100X_Coverage_pct FLOAT,
--     SdCoverage FLOAT,
--     SNP_Number FLOAT,
--     SNP_in_dbSNP FLOAT,
--     SNP_in_1KGP3 FLOAT,
--     SNP_in_gnomAD_exomes FLOAT,
--     SNP_in_gnomAD_genomes FLOAT,
--     SNP_in_TOPMed FLOAT,
--     SNP_in_ChinaMAP FLOAT,
--     Novel_SNP FLOAT,
--     Homozygous_SNP FLOAT,
--     Heterozygous_SNP FLOAT,
--     HIGH_impact_SNP FLOAT,
--     MODERATE_impact_SNP FLOAT,
--     LOW_impact_SNP FLOAT,
--     MODIFIER_impact_SNP FLOAT,
--     Het_Hom FLOAT,
--     Ti_Tv FLOAT,
--     INDEL_Number FLOAT,
--     INDEL_in_dbSNP FLOAT,
--     INDEL_in_1KGP3 FLOAT,
--     INDEL_in_gnomAD_exomes FLOAT,
--     INDEL_in_gnomAD_genomes FLOAT,
--     INDEL_in_TOPMed FLOAT,
--     INDEL_in_ChinaMAP FLOAT,
--     Novel_INDEL FLOAT,
--     Homozygous_INDEL FLOAT,
--     Heterozygous_INDEL FLOAT,
--     HIGH_impact_INDEL FLOAT,
--     MODERATE_impact_INDEL FLOAT,
--     LOW_impact_INDEL FLOAT,
--     MODIFIER_impact_INDEL FLOAT,
--     CNV_CNVnator_Number FLOAT,
--     CNV_CNVnator_DUP_Length FLOAT,
--     CNV_CNVnator_DEL_Length FLOAT,
--     CNV_CNVnator_Anno_Number FLOAT,
--     SV_lumpy_Number FLOAT,
--     SV_lumpy_Anno_Number FLOAT,
--     SV_delly_Number FLOAT,
--     SV_delly_Anno_Number FLOAT,
--     SV_manta_Number FLOAT,
--     SV_manta_Anno_Number FLOAT,
--     SV_MELT_Number FLOAT,
--     SV_MELT_Anno_Number FLOAT,
--     contamination_pct FLOAT,
-- 	Score FLOAT,
-- 	Note_Warning TEXT,
-- 	Judge TEXT,
--     -- is_bad INTEGER,
--     -- bad_note TEXT,
-- 	created TIMESTAMP DEFAULT (datetime('now','localtime'))
-- );
